//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTO.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firma()
        {
            this.Kullanici1 = new HashSet<Kullanici>();
            this.Rating = new HashSet<Rating>();
        }
    
        public int f_id { get; set; }
        public string f_ad { get; set; }
        public string f_yetkiliAdSoyad { get; set; }
        public string f_sehir { get; set; }
        public string f_ilce { get; set; }
        public string f_mahalle { get; set; }
        public Nullable<int> f_kategori { get; set; }
        public string f_adresDetay { get; set; }
        public string f_yetkiliTel { get; set; }
        public string f_sirketTel { get; set; }
        public string f_calismaSaat { get; set; }
        public Nullable<int> f_calismagun { get; set; }
        public string f_foto { get; set; }
        public string f_epota { get; set; }
        public Nullable<decimal> f_fiyat { get; set; }
        public Nullable<int> f_gelenMesaj { get; set; }
        public Nullable<int> f_kullanici { get; set; }
        public string f_detay { get; set; }
        public string f_ustaFoto { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanici> Kullanici1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Rating { get; set; }
        public virtual Gunler Gunler { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}
