//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTO.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.Firma = new HashSet<Firma>();
            this.Ilan = new HashSet<Ilan>();
        }
    
        public int k_id { get; set; }
        public string k_ad { get; set; }
        public string k_soyad { get; set; }
        public string k_eposta { get; set; }
        public string k_sifre { get; set; }
        public Nullable<int> k_gonderilenMesaj { get; set; }
        public Nullable<int> k_alinanMesaj { get; set; }
        public Nullable<bool> k_tipi { get; set; }
        public Nullable<int> k_firma { get; set; }
        public Nullable<int> k_ilan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Firma> Firma { get; set; }
        public virtual Firma Firma1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ilan> Ilan { get; set; }
        public virtual Ilan Ilan1 { get; set; }
    }
}
