//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTO.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaj
    {
        public int m_id { get; set; }
        public string m_gonderenAd { get; set; }
        public string m_aliciAd { get; set; }
        public string m_mesaj { get; set; }
        public Nullable<int> m_ilanMesaj { get; set; }
        public Nullable<int> m_firmaMesaj { get; set; }
    }
}
